/**
 * Sample conversations for each industry × personality combination.
 * Used by the WhatsApp preview component during signup.
 * Each industry has one typical customer question, and 8 personality-flavoured responses.
 */

export const INDUSTRY_QUESTIONS: Record<string, string> = {
  plumber: "Hi, do you do emergency callouts? My kitchen tap is leaking badly",
  electrician: "Hi, I need an EICR done on my rental property. How much?",
  builder: "We're looking to get a loft conversion done. Can you give us a quote?",
  landscaper: "Hi! We want our garden completely redesigned. Do you do free quotes?",
  roofer: "Got a leak coming through the ceiling after last night's rain. Can you help?",
  gardener: "Looking for someone to do regular garden maintenance. Monthly visits?",
  fencing: "Need about 30 metres of close board fencing. What's your rate?",
  paving: "Want the front drive done in block paving. Can you come take a look?",
  decking: "Thinking about getting composite decking in the back garden. Options?",
  "tree-surgeon": "Got a massive oak that needs reducing. It's overhanging the neighbour's",
  cleaner: "Need a deep clean for a 3-bed house. Moving out end of the month",
  dental: "Hi, I've got really bad toothache. Can I get an emergency appointment?",
  "estate-agent": "We're thinking of selling our 3-bed semi. What's the market like?",
  solicitor: "I need help with a house purchase. Do you handle conveyancing?",
  recruitment: "Looking for 3 qualified electricians for a 6-month contract in Leeds",
  "hair-salon": "Hi! Do you do balayage? Looking for a natural sun-kissed look",
  "dog-groomer": "My cockapoo is matted to bits. Can you fit him in this week?",
}

export const PERSONALITY_RESPONSES: Record<string, Record<string, string>> = {
  plumber: {
    professional: "Good afternoon. Yes, we provide 24/7 emergency plumbing services. A leaking tap would typically fall under our standard callout rate. I can have an engineer with you within 2 hours. May I take your postcode?",
    friendly: "Hey! Yes we do — sounds stressful, don't worry we'll sort it! We can get someone out to you within a couple of hours. What's your postcode and I'll check who's nearest? 🔧",
    confident: "Yep, emergency callouts are what we do best. Leaking tap — we'll have it sorted in no time. Our guys carry all the parts. Give me your postcode and I'll get someone dispatched now.",
    cheeky: "A leaking tap? Say no more — we'll be there before you need a snorkel! 😄 We do emergency callouts 24/7. What's your postcode? I'll get our nearest hero en route.",
    calm: "I understand that must be worrying. Yes, we absolutely cover emergency callouts. Let's get this sorted for you — there's no need to panic. Could you share your postcode so I can arrange the nearest available plumber?",
    energetic: "Oh no, a leak! Don't worry, we're ON IT! 🚀 Yes we do emergency callouts — 24/7, rain or shine! Drop me your postcode and we'll have someone there in a flash!",
    funny: "A leaking tap? That's a drip too far! 😂 Yes we do emergency callouts — we're like the SAS but with spanners. What's your postcode? We'll deploy the troops!",
    flirty: "Oh a leak? Don't worry love, we'll come rescue you! 💧 We do emergency callouts 24/7 — our guys are quick, reliable, and easy on the eyes 😉 What's your postcode?",
  },
  electrician: {
    professional: "Good day. Yes, we're fully qualified to carry out EICR inspections for rental properties. Our standard rate for a 3-bed property is from £150. When would suit you for an inspection?",
    friendly: "Hi there! Yes we do EICRs — we do loads of them for landlords. For a standard rental it's usually around £150-180. When do you need it done by? Happy to work around tenants too!",
    confident: "EICRs — that's our bread and butter. Fully certified, 24-hour turnaround on the certificate. From £150 depending on size. When do you need it? I'll lock you in.",
    cheeky: "EICR? We do those in our sleep! 😄 Literally... some of the old wiring we've seen could keep you up at night. From £150, certificate in 24 hours. When works for you?",
    calm: "Of course, we carry out EICR inspections regularly for landlords. It's a straightforward process — typically takes a couple of hours. Pricing starts from £150. What's convenient for you?",
    energetic: "EICRs? Absolutely! We do tonnes for landlords! 💡 Quick, thorough, certificate in your hands next day. From £150 — shall I book you in? What day works?",
    funny: "EICR? We'll make sure your rental isn't wired like a Christmas tree! 🎄 From £150, certificate faster than your tenants can complain about the heating. When shall we pop round?",
    flirty: "An EICR? We love making sure everything's... safely connected 😉 From £150, we'll have your rental sparking with approval. When can we come make your place shine?",
  },
  builder: {
    professional: "Good afternoon. Loft conversions are one of our core specialities. We'd be delighted to arrange a site visit to discuss your requirements and provide a detailed quotation. When would be convenient?",
    friendly: "Hi! A loft conversion — exciting project! We've done loads of them locally. Best thing is for us to pop round, have a look at the space, and chat through what you're after. Free quote, no pressure. When suits you?",
    confident: "Loft conversions — done dozens, know them inside out. Dormer, Velux, or hip-to-gable? Let's get a site visit booked and I'll have a detailed quote to you within 48 hours. When works?",
    cheeky: "Loft conversion? Time to stop storing Christmas decorations up there and start living! 😄 We'll come have a look, measure up, and give you a proper quote. No hard sell, just honest building. When's good?",
    calm: "A loft conversion is a great way to add space and value. We'd be happy to visit, assess the structure, and walk you through the options at your pace. Shall we arrange a convenient time?",
    energetic: "A loft conversion! Love it — one of my favourite projects! 🏗️ The transformation is always amazing. Let's get a site visit in the diary — I'll bring ideas and give you a solid quote. When are you free?",
    funny: "Loft conversion? Brilliant — finally somewhere to hide from the in-laws! 😂 We'll pop round, take measurements, and give you a quote that won't need emergency scaffolding to look at. When works?",
    flirty: "A loft conversion? That's ambitious — I like it! 😏 Let me come see the space and I'll sweep you off your feet with some design ideas. When can I pop round? I promise I'm worth the visit.",
  },
  landscaper: {
    professional: "Good afternoon. A full garden redesign is something we specialise in. We offer complimentary consultations where we assess the space and discuss your vision. Shall I arrange a convenient time to visit?",
    friendly: "Hi! Yes, absolutely — we love a full garden makeover! We do free quotes — I'll come round, have a look at the space, get a feel for what you're after, and put together some ideas. When are you free?",
    confident: "Full garden redesign? That's our sweet spot. Free site visit, 3D design if you want it, and a quote that covers everything. I've transformed hundreds of gardens. When can I come see yours?",
    cheeky: "A complete garden redesign? Now you're speaking my language! 🌿 Free quotes, big ideas, and we actually turn up when we say we will (revolutionary, I know). When shall I pop round?",
    calm: "How lovely — a fresh start for your garden. We'd be happy to come and discuss your ideas. There's no rush and no obligation. When would be a good time for a relaxed chat about what you envision?",
    energetic: "A full redesign?! YES! That's the dream project! 🌳 I've got so many ideas already! Free quote, free consultation, and I promise you'll be blown away. When can I come see the canvas?!",
    funny: "Complete garden redesign? Say no more — we'll make the neighbours so jealous they'll want to move! 😂 Free quotes, big dreams, and we even clean up after ourselves. Revolutionary. When suits?",
    flirty: "A complete garden redesign? Now you've got my attention 😍 I'd love to come see your outdoor space — I promise I'll make it beautiful. Free consultation, no strings attached. When works for you?",
  },
  solicitor: {
    professional: "Good afternoon. Yes, conveyancing is one of our core practice areas. We would be happy to assist with your purchase. If you could provide the property details, I can prepare a fee estimate for you promptly.",
    friendly: "Hi there! Yes, we handle conveyancing — we've helped hundreds of people through the process. It can feel overwhelming but we make it as smooth as possible. Send over the property details and I'll get you a quote today!",
    confident: "Conveyancing — absolutely. We handle the entire process start to finish. Fixed fees, no hidden costs, and we move fast. Send me the property details and I'll have your quote within the hour.",
    cheeky: "Conveyancing? We'll get you into that new house faster than you can argue about which room's the office! 😄 Send the property details over and I'll sort a quote before the kettle boils.",
    calm: "Of course, conveyancing is something we handle regularly. Buying a home is a big step, and we'll guide you through every stage with care. Please share the property details whenever you're ready.",
    energetic: "A house purchase — how exciting! 🏡 Yes we handle conveyancing! We'll make the legal bit as painless as possible so you can focus on the fun stuff. Send the details and I'll fire back a quote!",
    funny: "Conveyancing? We'll handle all the boring legal bits so you can focus on arguing about paint colours! 😂 Fixed fees, no surprises (except maybe the survey). Send over the details!",
    flirty: "A house purchase? How exciting — nesting instinct kicking in? 😏 We'll take care of all the legal romance. Send me the property details and I'll have a quote ready faster than you can pack a box.",
  },
  dental: {
    professional: "Good morning. I'm sorry to hear you're in pain. We do keep emergency slots available. May I take your name and contact number? I'll check our earliest availability and contact you shortly.",
    friendly: "Oh no, toothache is the worst! We keep emergency slots open for exactly this. Let me check what we've got today — what's your name and I'll get you sorted ASAP? Hang in there!",
    confident: "Toothache? We'll get you seen today. We always keep emergency slots open. Give me your name and number and I'll have a time confirmed for you within 10 minutes.",
    cheeky: "Toothache? That's right up there with stepping on Lego! 😬 Don't worry, we've got emergency slots. Let me check today's diary — what's your name? We'll have you smiling again in no time!",
    calm: "I'm sorry you're experiencing pain — that must be really uncomfortable. Please don't worry, we have emergency appointments available. Let me find the earliest slot for you. What's your name?",
    energetic: "Toothache? We'll fix that! 🦷 We keep emergency slots open every day — let's get you in and get you sorted! What's your name? I'll find the first available appointment right now!",
    funny: "Toothache? The tooth fairy's gone rogue! 🧚 Just kidding — we'll sort you out. We've got emergency slots today. What's your name? You'll be pain-free and cracking smiles by this afternoon!",
    flirty: "Toothache? Poor you! 😢 Don't worry, we'll take care of you — our dentists have very gentle hands 😉 Let me grab you an emergency slot today. What's your name, love?",
  },
  "hair-salon": {
    professional: "Good afternoon. Yes, balayage is one of our signature services. We offer a complimentary consultation to discuss your desired look and assess your hair. Would you like to book one?",
    friendly: "Hi lovely! Yes we do balayage — it's one of our most popular services! A natural sun-kissed look sounds gorgeous. Want to pop in for a free consultation? We'll chat about shades and technique!",
    confident: "Balayage is literally our thing — we've been doing it before it was trendy! Natural sun-kissed is totally achievable. Book a free consultation and I'll show you our portfolio. You'll love it.",
    cheeky: "Balayage? You had me at sun-kissed! ☀️ We're basically the Michelangelo of hair colour. Come in for a free consult — we'll have you looking like you just flew back from Ibiza!",
    calm: "What a lovely choice — balayage gives such a beautiful, natural result. We'd love to do a consultation to find the perfect tones for your hair. No rush, no pressure. Shall we book you in?",
    energetic: "Balayage?! OMG YES! 🌟 Sun-kissed is SO gorgeous — you're going to love it! Come in for a free consultation and we'll plan the perfect look. I'm already excited for you!",
    funny: "Balayage? Say no more — we'll have you looking so good your friends will accuse you of having a holiday you didn't tell them about! 😂 Free consult first? Shall I book you in?",
    flirty: "Balayage for a sun-kissed look? You're going to look absolutely stunning 😍 Come in for a free consultation — I'd love to find the perfect shades for you. When are you free, gorgeous?",
  },
  "dog-groomer": {
    professional: "Good afternoon. A matted cockapoo will require a thorough grooming session, which typically takes 1.5 to 2 hours. We have availability this week. Shall I check specific days for you?",
    friendly: "Oh bless him! Cockapoos are notorious for getting matted — don't feel bad! We can definitely fit him in this week. It'll take about 2 hours but he'll come out looking gorgeous. Which day works?",
    confident: "Matted cockapoo? We deal with those daily — no matt is too tough for us. I'll have him looking like a show dog. Got slots this week. Which day, and what's the little fella's name?",
    cheeky: "A matted cockapoo? He's gone full sheep mode! 🐑 Don't worry, we'll work our magic. He'll go in looking like a mop and come out like a model. Got space this week — what's his name?",
    calm: "Don't worry at all — matting happens, especially with cockapoos. We'll take really good care of him and get him comfortable again. We have time this week. What's his name, and when suits you?",
    energetic: "A matted cockapoo?! We LOVE cockapoos! 🐶 We'll have him fluffed up and fabulous in no time! Got slots this week — what's the little legend's name? Can't wait to meet him!",
    funny: "Matted cockapoo? He's basically wearing a onesie made of his own fur! 😂 We'll sort him out — he'll be so fluffy he'll need his own postcode. What's his name and when can we meet?",
    flirty: "A matted cockapoo? Poor baby! We'll pamper him like royalty 👑 He'll come out looking so handsome all the dogs in the park will swoon. What's his name? When shall we work our magic?",
  },
  roofer: {
    professional: "I'm sorry to hear about the leak. We can arrange an inspection at your earliest convenience. Our surveyors carry thermal imaging to locate the source precisely. May I take your address and postcode?",
    friendly: "Oh no — a ceiling leak is no fun! Don't worry, we'll get up there and find exactly where it's coming in. Can get someone out tomorrow if that works? What's your address?",
    confident: "Ceiling leak? We'll find it and fix it. We've got thermal cameras that pinpoint the source — no guessing. Can be there tomorrow morning. What's the address?",
    cheeky: "A leak after one night of rain? Sounds like your roof's been moonlighting as a colander! 😄 We'll sort it — got thermal cameras and everything. Tomorrow work for you?",
    calm: "That sounds worrying, but please don't panic — most leaks are fixable more easily than you'd expect. We can come and inspect it at a time that suits you. What's your address?",
    energetic: "A leak? We're on it! 🏠 Nothing we haven't seen before — we'll track it down and patch it up properly. Can be there first thing tomorrow! What's your address? Let's go!",
    funny: "Ceiling leak? Your roof's decided to install a water feature without permission! 😂 We'll come sort it before your living room becomes a paddling pool. Tomorrow good?",
    flirty: "A leak? Your roof needs some TLC — and lucky for you, we're experts at giving attention where it's needed 😉 We can pop round tomorrow. What's your address, love?",
  },
  "estate-agent": {
    professional: "Good afternoon. We'd be delighted to discuss the sale of your property. The current market for 3-bed semi-detached properties in your area is performing well. Shall we arrange a complimentary valuation?",
    friendly: "Hi! Great timing — the market for 3-bed semis is really strong right now. We'd love to come round, have a look at your place, and give you an honest valuation. Free, no obligation. When suits?",
    confident: "3-bed semi? The market's strong for those right now. We've sold 15 in your area this quarter alone. I'll come do a valuation — you'll have a price and a marketing plan within 48 hours. When works?",
    cheeky: "Thinking of selling? The market's hotter than a radiator in July right now! 🔥 3-bed semis are flying. Let me come value it — I promise I won't judge the state of the spare room. When shall I pop round?",
    calm: "Selling your home is a big decision, and there's no rush. The market for 3-bed properties is quite favourable at the moment. Would you like us to come and give you a no-obligation valuation when you're ready?",
    energetic: "3-bed semi? The market is BUZZING for those right now! 📈 You've picked a great time! Let me come do a free valuation — I've got some amazing marketing ideas. When can I pop over?!",
    funny: "Selling the 3-bed semi? Time to make someone else deal with that dodgy shower pressure! 😂 Market's great for semis right now. Free valuation, zero pressure, when shall I bring my measuring tape?",
    flirty: "Selling your lovely home? The market's going to love it as much as I bet the neighbours do 😏 Let me come take a look and tell you what it's really worth. When can I come charm you with numbers?",
  },
  recruitment: {
    professional: "Good afternoon. We can certainly assist with sourcing qualified electricians for your contract. We have an extensive network of CSCS-carded electrical professionals in the Leeds area. Shall I prepare a shortlist?",
    friendly: "Hi! 3 electricians for a 6-month contract in Leeds — we can definitely help with that! We've got a great network of qualified sparks in Yorkshire. Let me pull some profiles together for you. When do you need them to start?",
    confident: "3 qualified electricians for Leeds? Consider it done. We specialise in electrical trades recruitment — I can have CVs on your desk by end of play tomorrow. When's the start date?",
    cheeky: "3 sparks for Leeds? Easy peasy! We've got more electricians than Leeds has roundabouts! 😄 All qualified, all CSCS-carded. CVs tomorrow, interviews by Friday. When do they start?",
    calm: "Of course, we can help source qualified electricians for your contract. We'll take the time to find the right candidates who are properly qualified and reliable. What are the key requirements beyond electrical qualifications?",
    energetic: "3 electricians for Leeds?! We're ALL over this! ⚡ We've got a brilliant network of qualified sparks. CVs coming your way by tomorrow — when's the start date? Let's make this happen!",
    funny: "3 electricians for Leeds? We'll find you ones that actually turn up AND know which end of the wire to strip! 😂 CVs by tomorrow, all qualified, all real humans. What's the start date?",
    flirty: "3 electricians for 6 months? I love a good long-term arrangement 😉 We'll find you the best sparks in Leeds — all qualified, all ready to go. When shall we start this beautiful partnership?",
  },
  cleaner: {
    professional: "Good afternoon. We offer comprehensive end-of-tenancy deep cleaning for properties of all sizes. For a 3-bed house, our service typically takes 4-6 hours. May I schedule a convenient date?",
    friendly: "Hi! A deep clean for a move-out — we do loads of those! For a 3-bed it usually takes about half a day. We'll leave it landlord-inspection ready. When's your move-out date? Let's get you booked in!",
    confident: "End of tenancy deep clean for a 3-bed? We'll have it sparkling. We guarantee it passes the inventory check or we come back free. When's the move-out date? I'll lock the date in now.",
    cheeky: "Moving out deep clean? We'll make it look better than when you moved in — your landlord won't know what hit 'em! 😄 3-bed, half a day, deposit-saving results. When's the date?",
    calm: "Moving out can be stressful enough without worrying about the clean. We'll take care of everything thoroughly so you can focus on the move. When are you leaving? We'll work around your schedule.",
    energetic: "End of tenancy clean? We LOVE those! 🧹 There's nothing more satisfying than a sparkling house! 3-bed, we'll smash it in half a day. Deposit-back guarantee! When's moving day?",
    funny: "Deep clean for a move-out? We'll remove evidence of every takeaway, every pet hair, and that mysterious stain behind the sofa! 😂 Deposit-back guarantee. When's the big day?",
    flirty: "A deep clean? We'll make your 3-bed look so good even you'll want to move back in! 😍 Our team is thorough, detail-obsessed, and easy on the eyes. When's your move-out date?",
  },
  fencing: {
    professional: "Good afternoon. 30 metres of close board fencing is a substantial run. Our rates are competitive and include supply, fitting, and disposal of any existing fencing. Shall I arrange a site visit for an accurate quote?",
    friendly: "Hi! 30 metres of close board — nice size job! Best thing is for us to come have a look so we can give you an accurate quote. We'll need to check ground conditions and access. When suits you for a visit?",
    confident: "30 metres of close board? That's a solid day's work for our team. We'll supply, fit, and take away the old stuff. Let me come measure up and give you a price. Can do it this week.",
    cheeky: "30 metres of close board? Someone's serious about privacy! 😄 Or maybe the neighbours' dog? Either way, we'll sort it. Free site visit, honest quote. When can I come measure up?",
    calm: "30 metres is a good stretch. We'd want to come and see the site before quoting — ground conditions, access, and any existing fencing all affect the price. When would be convenient for a visit?",
    energetic: "30 metres of close board! Love a good fencing job! 🔨 We'll come measure up, give you a bang-on quote, and have it done before you know it. When can I come take a look?",
    funny: "30 metres? That's quite the boundary statement! 'Good fences make good neighbours' as they say! 😂 Free site visit, honest quote, and we won't sword-fight with the panels. When works?",
    flirty: "30 metres of fencing? You really know how to set boundaries — I respect that! 😏 Let me come take a look and give you a proper quote. When can I pop round?",
  },
  paving: {
    professional: "Good afternoon. Block paving for a front drive is one of our specialist services. We offer a range of styles and colours. I'd recommend a site visit to discuss options and provide an accurate quotation.",
    friendly: "Hi! Block paving on the front drive — great choice! It really transforms the look of a house. We'll need to pop round and measure up, chat about styles. Free quote, no obligation. When works for you?",
    confident: "Block paving — we've done hundreds of driveways. I know exactly what'll work for a front drive. Site visit, you pick the style and colour, we handle everything. When shall I come?",
    cheeky: "Block paving the front drive? Your house is about to get a serious glow-up! ✨ We'll come have a look, show you some styles, and give you a quote. Your neighbours will be so jealous. When suits?",
    calm: "Block paving is a wonderful choice for a front drive — it's durable and looks beautiful. We'd be happy to visit, show you some options, and take measurements. No rush. When's good for you?",
    energetic: "Block paving! YES! Your drive is about to look INCREDIBLE! 🎨 So many styles and colours to choose from. Let me come see the space and blow your mind with options. When are you free?!",
    funny: "Block paving the drive? Finally, somewhere to park that looks better than a mud wrestling ring after rain! 😂 We'll come measure up and show you styles. Free quote. When suits?",
    flirty: "Block paving? Your drive is about to become the best-looking one on the street 😍 I'd love to come show you some gorgeous styles. When can I pop round and sweep you off your feet?",
  },
  decking: {
    professional: "Good afternoon. Composite decking is an excellent low-maintenance choice. We offer several brands and colour options. A site visit would allow us to discuss your requirements and provide an accurate quotation.",
    friendly: "Hi! Composite decking is a great shout — looks amazing and basically zero maintenance. We've got loads of options. Want us to pop round with some samples? Free quote, nice and easy!",
    confident: "Composite decking — smart choice. We're approved installers for Trex and Millboard. I'll bring samples, measure up, and have a quote same day. When works for a site visit?",
    cheeky: "Composite decking? The future is now! No more yearly sanding and staining — just sit back with a G&T and enjoy 😎 I'll bring samples round. When can I pop over?",
    calm: "Composite decking is a lovely option — it weathers beautifully and needs very little upkeep. We'd be happy to bring some samples round and discuss what would work best in your garden.",
    energetic: "Composite decking! LOVE IT! 🌟 So many colours, so little maintenance — it's basically the dream! Let me bring samples round and we'll design something amazing. When are you free?!",
    funny: "Composite decking? Welcome to the 'never stain anything again' club! 🎉 We'll bring samples — warning: you'll want to move your kitchen outside. When can I pop round?",
    flirty: "Composite decking? Your garden's about to become the ultimate chill spot 😏 I'll bring some gorgeous samples round — I've got great taste, promise. When shall I come impress you?",
  },
  "tree-surgeon": {
    professional: "Good afternoon. Tree reduction work, particularly with overhanging branches, requires careful assessment. We're fully insured and NPTC qualified. Shall I arrange a site inspection at your convenience?",
    friendly: "Hi! A big oak reduction — we love those jobs! Especially when there's a neighbour situation. We'll come take a look, assess what needs doing, and make sure everyone's happy. When suits for a visit?",
    confident: "Overhanging oak? We deal with these all the time. Fully insured, NPTC qualified. I'll come assess it, plan the reduction, and give you a price. We'll sort the neighbour situation too. When works?",
    cheeky: "A massive oak overhanging the neighbour's? Nature's way of testing relationships! 🌳 We'll trim it back, keep everyone happy, and your tree stays healthy. Win-win-win. When can I take a look?",
    calm: "I understand — overhanging trees can cause concern between neighbours. We'll assess the oak carefully and recommend the best approach to reduce it while keeping it healthy. When would suit for a visit?",
    energetic: "A massive oak reduction! Now THAT'S a proper job! 🌳💪 We're NPTC qualified and fully insured — this is what we live for! Let me come see it. When are you around?",
    funny: "An oak overhanging the neighbour's? It's basically trespassing! 😂 We'll give it a good haircut — tree version of 'back and sides, please.' Fully insured. When can I come look?",
    flirty: "A massive oak that needs attention? I love a big tree 😏 We'll take care of it — gentle hands, professional results. When can I come admire your garden... I mean, assess the oak?",
  },
}

export function getPreviewConversation(industry: string, personality: string): { question: string; answer: string } {
  const question = INDUSTRY_QUESTIONS[industry] ?? INDUSTRY_QUESTIONS['plumber']
  const responses = PERSONALITY_RESPONSES[industry] ?? PERSONALITY_RESPONSES['plumber']
  const answer = responses[personality] ?? responses['friendly']
  return { question, answer }
}
